### ISSUE TITLE
Menambahkan Tautan ke Demo Aplikasi dan Sedikit Saran

### ISSUE THREAD

**Issue by jefrydco** [damarkrisnandi/code-highlight-vuex#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Damar. Mas juga sudah menambahkan gaya CSS sendiri. Luar biasa Mas!

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni

1. Menambahkan Tautan ke Demo Aplikasi
Menambahkan tautan ke demo aplikasi. Untuk yang menambahkan tautan ke demo aplikasi, kalau ngga salah bisa melalui bagian yang ada di sini Mas

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)

2. Hasil Build tidak Perlu di Unggah
Saya lihat di repositori terdapat hasil buildnya ya Mas. Menurut saya akan lebih baik jika hasil build tersebut tidak perlu diunggah ke repositori. Kalau boleh tahu Mas menggunggah ke Netlify nya menggunakan upload zip atau melalui proses build?

Semangat selalu ya! :muscle:

**Comment by damarkrisnandi** [comment]
saya upload ke netlify melalui proses build mas. itu maaf ada hasil build
yg terupload ke repository karena hasil mencoba-coba build melalui github
page namun beberapa kali gagal, sempat gagal build juga di netlify namun
juga gagal walaupun akhirnya juga berhasil. Terima kasih kritik dan
sarannya mas

Pada tanggal Rab, 21 Okt 2020 pukul 20.34 Jefry Dewangga <
notifications@github.com> menulis:

**Comment by jefrydco** [comment]
Siap Mas, terima kasih kembali. Semangat selalu ya! Kalau ada yang bingung, jangan segan-segan untuk bertanya :muscle:
